### ISSUE TITLE
Update fungible token standard: add a version number to the token contract and save it in the first on-chain state

### ISSUE THREAD

**Issue by Comdex** [MinaFoundation/mina-fungible-token#111]
In the current implementation of the token standard, a special `AccountUpdate` is used to store and update the token supply. This requires third-party infrastructure providers, such as block explorers, wallets, and other services, to accurately determine whether a token contract adheres to the standard in order to display the correct circulating supply and avoid double-counting. If I understand correctly, the current approach used by Minascan relies on the VerificationKeyHash of a contract to determine whether a token is a standard token. However, this method is unreliable, as it may fail to recognize some standard token contracts.

These contracts typically implement a custom `TokenAdminContract`. When we assign `FungibleToken.AdminContract` to our custom admin contract before compiling the token contract, the `VerificationKeyHash` changes. However, the token contract still adheres to the standard. Block explorers like Minascan might misidentify such contracts, leading to incorrect calculations and display of the token's circulating supply.

Therefore, to more easily identify whether the contract deployed on the chain is a standard token contract, we can stipulate that the first on-chain state field of the token contract is used to store a version number that can identify the standard of the used token. In this way, third-party service providers can track changes in token standards to properly handle corresponding token data.

**Comment by dfstio** [comment]
The verification key does not depend upon the admin contract, so you can safely use the verification key to detect FungibleToken contracts.

**Comment by Comdex** [comment]
> The verification key does not depend upon the admin contract, so you can safely use the verification key to detect FungibleToken contracts.

Based on my test results, setting `FungibleToken.AdminContract = MyCustomAdminContract `before compilation results in a different `VerificationKeyHash` if `MyCustomAdminContract `is a different contract.

**Comment by dfstio** [comment]
Can you please share the repo link? In my tests, the verification key is the same, and the change of the admin should not affect the verification key hash of the FungibleToken contract. Of course, the verification key of the Custom admin will be different.

**Comment by Comdex** [comment]
Opps, Sorry that It's a mistake!!  I double checked just know, And found it's a mistake related to cache. When I del the cache stuff, then the exec result meet the expectation.
