### ISSUE TITLE
Latest code not released on NPM

### ISSUE THREAD

**Issue by 45930** [MinaFoundation/mina-fungible-token#71]
The version of this package on NPM requires version `0.18.0` of o1js, which isn't compatible with version 1+.  It looks like the version on the `main` branch has a more up-to-date dependency, but it has not been released.

**Comment by kantp** [comment]
Thanks for flagging, I just published v1.0.0 on npm.

**Comment by L-as** [comment]
Does this mean the API is stable now?

**Comment by kantp** [comment]
Yes!
