### ISSUE TITLE
Can I have custom account updates?

### ISSUE THREAD

**Issue by L-as** [MinaFoundation/mina-fungible-token#89]
I want to have an account that holds a custom token that sends you the custom token under certain circumstances.
To support this, it needs to e.g. add actions, change app state, have children.
Having children alone is enough to do everything else.

So:
Can my account's account update have children, have authorization_kind be is_proved = true, and have a vk set, on e.g. token transfers?

**Comment by kantp** [comment]
You can have `AccountUpdate`s for token accounts that have children of their own, yes. You can pass a whole `AccountUpdateForest` to the `approveBase()` method.
